// SignalWire WebSocket Stream Handler
// Handles real-time audio streaming for voice calls

import { createHmac } from "crypto";
import type { IncomingMessage } from "http";
import type WebSocket from "ws";
import { createTurnManager } from "../services/voice/turn-manager.js";
import { getTenantById } from "../services/database/tenant-cache.js";
import { transferCall } from "../services/signalwire/client.js";

interface StreamParams {
  callSid: string;
  tenantId: string;
  callerPhone?: string;
  token: string;
}

/**
 * Validate the HMAC stream token generated by the voice route.
 * Accepts tokens from the current and previous 2 minute windows.
 */
function validateStreamToken(callSid: string, tenantId: string, token: string): boolean {
  const secret = process.env.STREAM_SIGNING_SECRET || process.env.SIGNALWIRE_API_TOKEN || "dev-stream-secret";
  const currentMinute = Math.floor(Date.now() / 60000);

  for (let offset = 0; offset <= 2; offset++) {
    const payload = `${callSid}:${tenantId}:${currentMinute - offset}`;
    const expected = createHmac("sha256", secret).update(payload).digest("hex").slice(0, 32);
    if (token === expected) return true;
  }
  return false;
}

/**
 * Parse query parameters from WebSocket URL
 */
function parseParams(url: string): StreamParams | null {
  try {
    const searchParams = new URL(url, "http://localhost").searchParams;
    const callSid = searchParams.get("callSid");
    const tenantId = searchParams.get("tenantId");
    const callerPhone = searchParams.get("callerPhone") || undefined;
    const token = searchParams.get("token");

    if (!callSid || !tenantId || !token) {
      return null;
    }

    return { callSid, tenantId, callerPhone, token };
  } catch {
    return null;
  }
}

/**
 * Handle WebSocket connection for media stream
 */
export async function handleSignalWireStream(
  ws: WebSocket,
  request: IncomingMessage,
): Promise<void> {
  const url = request.url || "";
  console.log(`[STREAM] New connection: ${url}`);

  // Parse parameters
  const params = parseParams(url);
  if (!params) {
    console.error("[STREAM] Missing required parameters");
    ws.close(1008, "Missing parameters");
    return;
  }

  const { callSid, tenantId, callerPhone, token } = params;

  // Validate stream token before processing
  if (!validateStreamToken(callSid, tenantId, token)) {
    console.error(`[STREAM] Invalid stream token for call ${callSid}`);
    ws.close(1008, "Invalid token");
    return;
  }

  console.log(`[STREAM] Call ${callSid} from ${callerPhone || "unknown"}`);

  // Get tenant
  const tenant = await getTenantById(tenantId);
  if (!tenant) {
    console.error(`[STREAM] Tenant not found: ${tenantId}`);
    ws.close(1008, "Tenant not found");
    return;
  }

  console.log(`[STREAM] Tenant: ${tenant.business_name}`);

  // Create turn manager
  const turnManager = createTurnManager(callSid, tenant, callerPhone, {
    onResponse: (text) => {
      console.log(`[STREAM] Response: "${text.substring(0, 50)}..."`);
    },
    onTransferRequested: (phoneNumber) => {
      console.log(`[STREAM] Transfer requested to: ${phoneNumber}`);
      const backendUrl = process.env.BACKEND_URL || "http://localhost:3100";
      void transferCall(callSid, phoneNumber, backendUrl).then((result) => {
        if (!result.success) {
          console.error(`[STREAM] Transfer failed: ${result.error}`);
        }
      });
    },
    onCallEnd: (reason) => {
      console.log(`[STREAM] Call ended: ${reason}`);
    },
  });

  try {
    // Initialize voice pipeline
    await turnManager.initialize(ws);
    console.log(`[STREAM] Voice pipeline initialized for ${callSid}`);
  } catch (error) {
    console.error(`[STREAM] Failed to initialize:`, error);
    ws.close(1011, "Initialization failed");
    return;
  }

  // Handle WebSocket close
  ws.on("close", async (code, reason) => {
    console.log(`[STREAM] Connection closed: ${code} ${reason}`);
    await turnManager.cleanup("completed");
  });

  ws.on("error", async (error) => {
    console.error(`[STREAM] WebSocket error:`, error);
    await turnManager.cleanup("error");
  });
}

/**
 * Check if a request is for the SignalWire stream
 */
export function isSignalWireStreamRequest(url: string): boolean {
  return url.startsWith("/signalwire/stream");
}
